name: "lint protobuf"
on: push

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: run protolint
        uses: plexsystems/protolint-action@v0.4.0
        with:
          configDirectory: .